# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-04 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('backend', '0001_initial'), ('backend', '0002_auto_20160721_0309'), ('backend', '0003_auto_20160802_1648'), ('backend', '0004_auto_20160925_1453'), ('backend', '0005_auto_20160925_1546'), ('backend', '0006_auto_20161003_1738'), ('backend', '0007_auto_20161003_1840'), ('backend', '0008_auto_20161003_1908')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(max_length=1)),
                ('city_name', models.CharField(blank=True, default='', max_length=255)),
                ('is_page_owned', models.BooleanField(default=False)),
                ('attending_count', models.IntegerField(null=True)),
                ('interested_count', models.IntegerField(null=True)),
                ('cover_image_url', models.URLField(blank=True, default='', max_length=1024)),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=50, unique=True, verbose_name='ID Externo')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('external_type', models.CharField(max_length=50, verbose_name='Tipo')),
                ('status', models.CharField(max_length=1, verbose_name='Status')),
                ('active', models.BooleanField(default=False, verbose_name='Ativo')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.Owner'),
        ),
        migrations.AlterField(
            model_name='event',
            name='attending_count',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='interested_count',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, default=None, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, default=None, max_digits=17, null=True),
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_time', 'name']},
        ),
        migrations.AlterField(
            model_name='event',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='event',
            name='attending_count',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Confirmados'),
        ),
        migrations.AlterField(
            model_name='event',
            name='city_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='event',
            name='cover_image_url',
            field=models.URLField(blank=True, default='', max_length=1024, verbose_name='URL da imagem de capa'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Término'),
        ),
        migrations.AlterField(
            model_name='event',
            name='external_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='ID Externo'),
        ),
        migrations.AlterField(
            model_name='event',
            name='interested_count',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Interessados'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_page_owned',
            field=models.BooleanField(default=False, verbose_name='Criado por Página'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='event',
            name='city_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='event',
            name='cover_image_url',
            field=models.URLField(blank=True, default='', max_length=1024, null=True, verbose_name='URL da imagem de capa'),
        ),
    ]
