# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-04 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_squashed_0008_auto_20161003_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='origin',
            field=models.CharField(choices=[('L', 'Robô PHP legado'), ('C', 'Mr. Crowley'), ('U', 'Usuário')], default='L', max_length=1, verbose_name='Origem de dados'),
        ),
        migrations.AddField(
            model_name='event',
            name='place_address',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='event',
            name='place_city',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='event',
            name='place_country',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='event',
            name='place_latitude',
            field=models.DecimalField(blank=True, decimal_places=15, default=None, max_digits=17, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='event',
            name='place_longitude',
            field=models.DecimalField(blank=True, decimal_places=15, default=None, max_digits=17, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='event',
            name='place_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Local'),
        ),
        migrations.AddField(
            model_name='event',
            name='place_state',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='owner',
            name='origin',
            field=models.CharField(choices=[('L', 'Robô PHP legado'), ('C', 'Mr. Crowley'), ('U', 'Usuário')], default='L', max_length=1, verbose_name='Origem de dados'),
        ),
        migrations.AddField(
            model_name='owner',
            name='owner_type',
            field=models.CharField(choices=[('U', 'Usuário'), ('P', 'Página')], default='U', max_length=1, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('P', 'Moderação pendente'), ('A', 'Aprovado'), ('D', 'Rejeitado')], default='P', max_length=1, verbose_name='Moderação'),
        ),
    ]
