# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-04 20:19
from __future__ import unicode_literals
from django.db import migrations


def migrate_owner_owner_type(apps, schema_editor):
    """Migra o campo `external_type` para `owner_type`."""
    Owner = apps.get_model("backend", "Owner")
    for owner in Owner.objects.all():
        owner.owner_type = 'P' if owner.external_type == 'page' else 'U'
        owner.save()


def migrate_event_place_city(apps, schema_editor):
    """Migra o campo `city_name` para `place_city`."""
    Event = apps.get_model("backend", "Event")
    for event in Event.objects.all():
        event.place_city = event.city_name
        event.save()


def migrate_event_place_latitude(apps, schema_editor):
    """Migra o campo `latitude` para `place_latitude`."""
    Event = apps.get_model("backend", "Event")
    for event in Event.objects.all():
        event.place_latitude = event.latitude
        event.save()


def migrate_event_place_longitude(apps, schema_editor):
    """Migra o campo `longitude` para `place_longitude`."""
    Event = apps.get_model("backend", "Event")
    for event in Event.objects.all():
        event.place_longitude = event.longitude
        event.save()


class Migration(migrations.Migration):
    """Define as migrações de dados para os modelos Owner e Event."""

    dependencies = [
        ('backend', '0002_auto_20161004_1718'),
    ]

    operations = [
        migrations.RunPython(migrate_owner_owner_type),
        migrations.RunPython(migrate_event_place_city),
        migrations.RunPython(migrate_event_place_latitude),
        migrations.RunPython(migrate_event_place_longitude),
    ]
