# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-28 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20161004_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='location_city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='owner',
            name='location_state',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='owner',
            name='notes',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Notas'),
        ),
    ]
