# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-03 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20160925_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Descrição'),
        ),
    ]
