# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-03 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20161003_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='city_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Cidade'),
        ),
    ]
