# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-25 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowley', '0002_auto_20160925_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawler',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='crawler',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='crawler',
            name='token',
            field=models.CharField(max_length=255, verbose_name='Token'),
        ),
    ]
